In [54]:
softmax_output = [0.7, 0.1, 0.2]
target_output = [1, 0, 0] # this is not in One hot encoding

In [55]:
new= zip(softmax_output,target_output)
list(new)

[(0.7, 1), (0.1, 0), (0.2, 0)]

In [58]:
softmax_output2 = [[0.7, 0.1, 0.2],[0.05,0.9,0.05],[0.2,0.78,0.2]]
target_output2 = [0, 1, 1]  # # this is not in One hot encoding, but it is in form of scalar values
new2= zip(softmax_output2,target_output2)
list(new2)

[([0.7, 0.1, 0.2], 0), ([0.05, 0.9, 0.05], 1), ([0.2, 0.78, 0.2], 1)]

In [59]:
#To bring coresponsding value 

softmax_output2 = [[0.7, 0.1, 0.2],[0.05,0.9,0.05],[0.2,0.78,0.2]]
target_output2 = [0, 1, 1]  # # this is not in One hot encoding

for sindex,tindex in zip(softmax_output2,target_output2):
    print(sindex[tindex])

0.7
0.9
0.78


In [60]:
# Without zip(), we can do it by numpy
import numpy as np
softmax_output2 =np.asarray(softmax_output2) # change to array
softmax_output2

array([[0.7 , 0.1 , 0.2 ],
       [0.05, 0.9 , 0.05],
       [0.2 , 0.78, 0.2 ]])

In [61]:
softmax_output2[[0,1,2],target_output2]

array([0.7 , 0.9 , 0.78])

In [63]:
len(softmax_output2)
range(len(softmax_output2))
print(range(4)) #Number of integers (whole numbers) to generate, starting from zero
d=range(len(softmax_output2))
print(range(len(softmax_output2)))
print(d)

range(0, 4)
range(0, 3)
range(0, 3)


In [65]:
# Without zip(), we can do it by numpy and programmatically 
softmax_output2[range(len(softmax_output2)),target_output2]

array([0.7 , 0.9 , 0.78])

In [66]:
-np.log(softmax_output2[range(len(softmax_output2)),target_output2])  #  loss function value for every element in batch
# We can see 0.1 value has low loss value because the propability value (softmax_output2) was high (0.9)

array([0.35667494, 0.10536052, 0.24846136])

In [53]:
# but in case of any input value is zero , will retun infinity, it is Game Over, just because of one value is zero :) 
np.log(0)

C:\Users\Ahmed\ana\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  


-inf