In [2]:
import numpy as np

In [23]:
x = [[1,-3.1,2.2],[1.9,1.8,2.17],[3.3,-0.4,0.9]]

In [24]:
print(np.exp(x)) # this is not what we need, we need to make sum for every row(set of element(a batch)) 
print()
print(np.sum(np.exp(x))) # this is not what we need, we need to make sum for every row(set of element(a batch)), not all
print()
print(np.sum(np.exp(x), axis=1))
print()
print(np.exp(x)/np.sum(np.exp(x), axis=1))  # but this is wrong answer, because i need each element in sum_matrix used with the first row with another matrix, not column like this reulst
print()
print(np.sum(np.exp(x), axis=1, keepdims=True)) # make sum with keeping the same shape and dimension
print()
print(np.exp(x)/np.sum(np.exp(x), axis=1, keepdims=True)) # This what i need: every row is divided by every element in sum_matric

[[ 2.71828183  0.0450492   9.0250135 ]
 [ 6.68589444  6.04964746  8.75828404]
 [27.11263892  0.67032005  2.45960311]]

63.524732555570246

[11.78834453 21.49382595 30.24256208]

[[2.30590633e-01 2.09591361e-03 2.98420930e-01]
 [5.67161439e-01 2.81459777e-01 2.89601259e-01]
 [2.29995305e+00 3.11866323e-02 8.13291911e-02]]

[[11.78834453]
 [21.49382595]
 [30.24256208]]

[[0.23059063 0.0038215  0.76558786]
 [0.31106116 0.28145978 0.40747906]
 [0.89650602 0.02216479 0.08132919]]


In [32]:
# Exponential function has overflow problem with largest values, so we will subtract input values from max_value before applying exponential function
# This will not impact the results, since we will deal with probability at the end(value/sum)
# For example:
T = [[1,-3.1,2.2],[1.9,1.8,2.17],[3.3,-0.4,0.9]]
exp1= np.exp(T)
exp2= np.exp(T-np.max(T))
print(exp1/np.sum(exp1, axis=1, keepdims=True))
print(exp2/np.sum(exp2, axis=1, keepdims=True))
# Two Results are similar but the second way will be used to avoid overflow problem for exponential function

[[0.23059063 0.0038215  0.76558786]
 [0.31106116 0.28145978 0.40747906]
 [0.89650602 0.02216479 0.08132919]]
[[0.23059063 0.0038215  0.76558786]
 [0.31106116 0.28145978 0.40747906]
 [0.89650602 0.02216479 0.08132919]]
