In [1]:
import numpy as np

In [6]:
# np.random.seed(0)
X = [[1,2,3,2.5],[2,5,-1,2],[-1.5,2.7,3.3,-0.8]]  # Input Matrix(3,4)
# https://github.com/Sentdex/NNfSiX/blob/master/Python/p004-Layers-and-Object.py

In [7]:
# We will intial weight randomly, so the dimension of Weights should be matrix(4,N) as the input is matrx(3,4)
    
class Layer_Dense:
    # we need to generate Weights and Biases
    def __init__(self, n_inputs, n_neurons): 
        # here as we do transpose for input (X (3,4)) to consider the numer of samples (4 for X) in matrx multiplication and becomes important to determine shape of weight matrix (number of rows (4, desire neuron))
        #and size of samples (batch size for X) are used in only calcuation but not impotant in determing shape of weight,
        #Where n_inputs is structure of input (4 nurons) or previous layer (last output), n_neurons is samples (we can say batch size) which is desire output nurons
        self.weights = 0.1 * np.random.randn(n_inputs, n_neurons)     # 0.1 to ensure that the range of values is low ( less than 1)
        self.biases = np.zeros((1,n_neurons))   # biases we will be added to output of sum of weights so should be matrix(1,N )
        
    def forward(self,inputs):  # inputs is last ouput
        self.output = np.dot(inputs,self.weights)+self.biases

In [8]:
class Activation_Rellu:
    def forward(self, inputs): # inputs here is output of summation of wieghts and neurons
        self.output = np.maximum(0,inputs)


In [11]:
# let us to create two layers: input layer and 1st hidden layer

layer1= Layer_Dense(4,5)  # takes two paramters (number of features (input neurons) here X (every sampel has 4 neurons or features) and batch size or samples)
layer2= Layer_Dense(5,3) # we choose 5 to be like previous output neurons 
# layer3= Layer_Dense(3,3)

Activation1 = Activation_Rellu()
Activation2 = Activation_Rellu()

layer1.forward(X)
Activation1.forward(layer1.output)
layer2.forward(Activation1.output)
Activation2.forward(layer2.output)
# layer3.forward(layer2.output)

In [12]:
print(layer1.output)  # as Input_Matrix:X(3,4)* Weights(4,5) = output(3,5)
# print(layer2.output)  # as Input_Matrix:last layer ouput(3,5)* Weights(5,3) = output(3,3)
# print(layer3.output) #  (3,3) * (3,3)=(3,3)
print(Activation1.output) # all negative values become zero becuase of Relu function

[[-0.62000104  0.29137294 -0.34475891 -0.75288288  0.24600957]
 [-0.62052457  1.08432252 -0.28839038 -0.93227544 -0.09180112]
 [-0.1593076  -0.04861024 -0.05664166 -0.66619194 -0.22422852]]
[[0.         0.29137294 0.         0.         0.24600957]
 [0.         1.08432252 0.         0.         0.        ]
 [0.         0.         0.         0.         0.        ]]


In [13]:
print(layer2.output)  # as Input_Matrix:last layer ouput(3,5)* Weights(5,3) = output(3,3)
print(Activation2.output) # all negative values become zero becuase of Relu function

[[-0.04184293  0.02185091  0.01518896]
 [-0.12272638  0.01665685 -0.01378473]
 [ 0.          0.          0.        ]]
[[0.         0.02185091 0.01518896]
 [0.         0.01665685 0.        ]
 [0.         0.         0.        ]]
