In [1]:
import numpy as np

# Create Data
#https://cs231n.github.io/neural-networks-case-study/
# https://gist.github.com/Sentdex/454cb20ec5acf0e76ee8ab8448e6266c
# points = 100 # number of points per class
# D = 2 # dimensionality
# classes = 3 # number of classes
def spiral_data(points, classes):
    X = np.zeros((points*classes, 2))  # data matrix  # D = 2 # dimensionality
    y = np.zeros(points*classes, dtype='uint8')   #class labels
    for class_number in range(classes):
        ix = range(points*class_number, points*(class_number+1))
        r = np.linspace(0.0, 1, points)  # radius
        t = np.linspace(class_number*4, (class_number+1)*4, points) + np.random.randn(points)*0.2
        X[ix] = np.c_[r*np.sin(t*2.5), r*np.cos(t*2.5)]
        y[ix] = class_number
    return X, y


In [5]:
# We will intial weight randomly, so the dimension of Weights should be matrix(4,N) as the input is matrx(3,4)
    
class Layer_Dense:
    # we need to generate Weights and Biases
    def __init__(self, n_inputs, n_neurons): 
        self.weights = 0.1 * np.random.randn(n_inputs, n_neurons)     # 0.1 to ensure that the range of values is low ( less than 1)
        self.biases = np.zeros((1,n_neurons))   # biases we will be added to output of sum of weights so should be matrix(1,N )
        
    def forward(self,inputs):  # inputs is last ouput
        self.output = np.dot(inputs,self.weights)+self.biases

        
class Activation_Rellu:
    def forward(self, inputs): # inputs here is output of summation of wieghts and neurons
        self.output = np.maximum(0,inputs)
        
        
class Activation_Softmax:
    def forward(self, inputs):
        exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
        probabilities = exp_values / np.sum(exp_values, axis=1, keepdims=True)
        self.output = probabilities
        

In [18]:
# X, y = spiral_data(samples_batch=100, classes_indata=3)
X, y = spiral_data(points=100, classes=3)

layer1= Layer_Dense(2,5)  # X has two features(neurons) as input, 5 is my desire neurons
Activation1 = Activation_Rellu()

layer2= Layer_Dense(5,4) # we choose 5 to be like previous output neurons and 4 is my desire neurons
Activation2 = Activation_Rellu()

layer3= Layer_Dense(4,3)
Activation3 = Activation_Softmax()


layer1.forward(X)
Activation1.forward(layer1.output)

layer2.forward(Activation1.output)
Activation2.forward(layer2.output)
Activation2.output.shape

layer3.forward(Activation2.output)
Activation3.forward(layer3.output)

print(Activation3.output.shape)
print(Activation3.output[:5])
# print(Activation3.output)

(300, 3)
[[0.33333333 0.33333333 0.33333333]
 [0.33333331 0.33333343 0.33333325]
 [0.33333333 0.33333333 0.33333333]
 [0.33333328 0.33333361 0.33333311]
 [0.33334598 0.33334946 0.33330456]]
