In [ ]:
import numpy as np

In [3]:
# Create Data
#https://cs231n.github.io/neural-networks-case-study/
# https://gist.github.com/Sentdex/454cb20ec5acf0e76ee8ab8448e6266c
# points = 100 # number of points per class
# D = 2 # dimensionality
# classes = 3 # number of classes
def spiral_data(points, classes):
    X = np.zeros((points*classes, 2))  # data matrix  # D = 2 # dimensionality
    y = np.zeros(points*classes, dtype='uint8')   #class labels
    for class_number in range(classes):
        ix = range(points*class_number, points*(class_number+1))
        r = np.linspace(0.0, 1, points)  # radius
        t = np.linspace(class_number*4, (class_number+1)*4, points) + np.random.randn(points)*0.2
        X[ix] = np.c_[r*np.sin(t*2.5), r*np.cos(t*2.5)]
        y[ix] = class_number
    return X, y

In [6]:
# We will intial weight randomly, so the dimension of Weights should be matrix(4,N) as the input is matrx(3,4)
    
class Layer_Dense:
    # we need to generate Weights and Biases
    def __init__(self, n_inputs, n_neurons): 
        self.weights = 0.1 * np.random.randn(n_inputs, n_neurons)     # 0.1 to ensure that the range of values is low ( less than 1)
        self.biases = np.zeros((1,n_neurons))   # biases we will be added to output of sum of weights so should be matrix(1,N )
        
    def forward(self,inputs):  # inputs is last ouput
        self.output = np.dot(inputs,self.weights)+self.biases

        
class Activation_Rellu:
    def forward(self, inputs): # inputs here is output of summation of wieghts and neurons
        self.output = np.maximum(0,inputs)

In [9]:
# let us to create two layers: input layer and 1st hidden layer
X, y = spiral_data(100, 3) # input matrix (100,3) 100 samples and three classes in data, X has two dimensions, y is label  
layer1= Layer_Dense(2,5)  # takes two paramters (number of features (input neurons) here X (every sampel has 2 neurons or features) and batch size or samples)
layer2= Layer_Dense(5,3) # we choose 5 to be like previous output neurons 
# layer3= Layer_Dense(3,3)

Activation1 = Activation_Rellu()
Activation2 = Activation_Rellu()

layer1.forward(X)
Activation1.forward(layer1.output)
layer2.forward(Activation1.output)
Activation2.forward(layer2.output)
# layer3.forward(layer2.output)

In [10]:
print(layer1.output)  # as Input_Matrix:X(100,2)* Weights(2,5) = output(100,5)
print(Activation1.output) # all negative values become zero becuase of Relu function

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00]
 [-2.81917252e-04  7.20191070e-05  4.18048657e-04  4.35505076e-04
  -3.33443787e-04]
 [-1.31772490e-03  1.47373503e-03  2.01869250e-03  9.80893529e-04
  -6.29053411e-04]
 ...
 [ 6.28205439e-02 -1.22016175e-01 -9.91816459e-02  1.24565977e-03
  -1.23198709e-02]
 [ 9.19074169e-02 -1.41387744e-01 -1.42993001e-01 -3.26117963e-02
   1.23222467e-02]
 [ 5.41861889e-02 -1.12691531e-01 -8.59730998e-02  7.98084906e-03
  -1.67130844e-02]]
[[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 7.20191070e-05 4.18048657e-04 4.35505076e-04
  0.00000000e+00]
 [0.00000000e+00 1.47373503e-03 2.01869250e-03 9.80893529e-04
  0.00000000e+00]
 ...
 [6.28205439e-02 0.00000000e+00 0.00000000e+00 1.24565977e-03
  0.00000000e+00]
 [9.19074169e-02 0.00000000e+00 0.00000000e+00 0.00000000e+00
  1.23222467e-02]
 [5.41861889e-02 0.00000000e+00 0.00000000e+00 7.98084906e-03
  0.00000000e+00]

In [11]:
print(layer2.output)  # as Input_Matrix:last layer ouput(100,5)* Weights(5,3) = output(100,3)
print(Activation2.output) # all negative values become zero becuase of Relu function

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 4.41491779e-05 -9.29515835e-05 -6.42353681e-05]
 [ 3.88860782e-04 -3.74301956e-04 -1.70880086e-04]
 [ 8.93925675e-04 -7.16245590e-04 -2.64678209e-04]
 [ 1.11878872e-03 -9.24938549e-04 -3.56603725e-04]
 [ 1.56685348e-03 -1.21969276e-03 -4.32175295e-04]
 [ 1.61599278e-03 -1.35922306e-03 -5.35725105e-04]
 [ 2.12931981e-03 -1.68702294e-03 -6.13518947e-04]
 [ 2.64375771e-03 -1.97776262e-03 -6.57919139e-04]
 [ 2.99414414e-03 -2.22526449e-03 -7.32125996e-04]
 [ 2.92223227e-03 -1.81863254e-03 -3.55082201e-04]
 [ 3.72478763e-03 -2.70845161e-03 -8.57616520e-04]
 [ 3.83392086e-03 -2.94647894e-03 -1.02373966e-03]
 [ 4.40836426e-03 -3.19815603e-03 -1.00847305e-03]
 [ 1.69296426e-03 -2.00124832e-03 -1.07421618e-03]
 [ 4.64624359e-03 -2.93996169e-03 -6.33890060e-04]
 [ 4.86426413e-03 -3.06074257e-03 -6.39037688e-04]
 [ 3.90394849e-03 -2.65937067e-03 -5.88561166e-04]
 [ 5.92756478e-03 -3.83646340e-03 -9.31488587e-04]
 [ 4.65928556e-03 -4.08011777e-

In [13]:
Activation2.output.ndim

2

In [14]:
Activation2.output.shape

(300, 3)